apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.providerConfig.name }}
  annotations:
    # Apply after Provider
    argocd.argoproj.io/sync-wave: "1"
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ default (default .Release.Namespace .Values.global.targetNamespace) .Values.providerConfig.credentials.secretNamespace }}
      name: {{ .Values.providerConfig.credentials.secretName }}
      key: {{ .Values.providerConfig.credentials.secretKey }}
