# templates/10-providerconfig.yaml
apiVersion: aws.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: {{ .Values.providerConfig.name }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # ProviderConfig after Provider
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: {{ default .Release.Namespace .Values.providerConfig.credentials.secretNamespace }}
      name: {{ .Values.providerConfig.credentials.secretName }}
      key: {{ .Values.providerConfig.credentials.secretKey }}
