apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: {{ .Values.provider.name }}
  annotations:
    # Ensure Provider applies before ProviderConfig in Argo CD
    argocd.argoproj.io/sync-wave: "0"
spec:
  package: {{ .Values.provider.package | quote }}
