{{- /*
Upgraded Argo CD Application generator with resource cleanup.
*/ -}}
{{- $d := .Values.defaults -}}
{{- range $i, $app := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ required "apps[].name is required" $app.name | trunc 63 | trimSuffix "-" }}
  namespace: {{ $d.appNamespace | default "argocd" }}
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: {{ $.Release.Name }}
  annotations:
    # Ensures resources created by this Application are deleted when the Application is deleted
    argocd.argoproj.io/finalizer: resources-finalizer.argocd.argoproj.io
    # Optional: ensures resources are pruned in the correct order (CRDs last)
    argocd.argoproj.io/sync-options: PruneLast=true
spec:
  project: {{ $d.project | default "default" }}
  source:
    repoURL: {{ $d.repoURL | quote }}
    targetRevision: {{ $d.targetRevision | default "main" | quote }}
    {{- if $app.path }}
    path: {{ $app.path | quote }}
    {{- else if $app.chart }}
    chart: {{ $app.chart | quote }}
    {{- else }}
    {{- fail "Provide apps[].path (monorepo) or apps[].chart (repo chart)" }}
    {{- end }}
    helm:
      releaseName: {{ default $app.name $app.releaseName | quote }}

      {{- /* valueFiles logic */ -}}
      {{- $files := list -}}
      {{- if $app.valuesFiles }}{{- $files = $app.valuesFiles -}}{{- end -}}
      {{- if and (not $app.valuesFiles) $app.valuesFile }}{{- $files = list $app.valuesFile -}}{{- end -}}
      {{- if and (eq (len $files) 0) $d.defaultValuesFile }}{{- $files = list $d.defaultValuesFile -}}{{- end -}}
      {{- if gt (len $files) 0 }}
      valueFiles:
      {{- toYaml $files | nindent 6 }}
      {{- end }}

      {{- /* inline values */ -}}
      {{- if $app.values }}
      values: |
        {{- toYaml $app.values | nindent 8 }}
      {{- end }}

  destination:
    server: {{ $d.destinationServer | default "https://kubernetes.default.svc" | quote }}
    namespace: {{ required "apps[].namespace (destination) is required" $app.namespace | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: {{ $d.revisionHistoryLimit | default 5 }}
---
{{- end }}
