{{- if and .Values.kyverno.enabled .Values.kyverno.rbac.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-kyverno-rds-read" .Release.Name }}
rules:
  - apiGroups:
      {{- toYaml .Values.kyverno.rbac.apiGroups | nindent 6 }}
    resources:
      {{- toYaml .Values.kyverno.rbac.resources | nindent 6 }}
    verbs:
      {{- toYaml .Values.kyverno.rbac.verbs | nindent 6 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ printf "%s-kyverno-rds-read" .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ printf "%s-kyverno-rds-read" .Release.Name }}
subjects:
{{- range .Values.kyverno.rbac.subjects }}
  - kind: ServiceAccount
    name: {{ .serviceAccountName }}
    namespace: {{ .namespace | default "kyverno" }}
{{- end }}
{{- end }}
