{{- if .Values.kyverno.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: {{ default "disallow-public-rds" .Values.kyverno.policy.name }}
spec:
  validationFailureAction: {{ default "Enforce" .Values.kyverno.policy.validationFailureAction }}
  background: {{ default true .Values.kyverno.policy.background }}
  rules:
    - name: {{ default "validate-rds" .Values.kyverno.policy.ruleName }}
      match:
        resources:
          kinds:
          {{- range $k := (default (list "database.aws.crossplane.io/v1beta1/RDSInstance") .Values.kyverno.policy.match.kinds) }}
            - {{ $k | quote }}
          {{- end }}
      validate:
        {{- with .Values.kyverno.policy.message }}
        message: {{ . | quote }}
        {{- end }}
        {{- if .Values.kyverno.policy.anyPattern }}
        anyPattern:
{{ toYaml .Values.kyverno.policy.anyPattern | nindent 10 }}
        {{- else if .Values.kyverno.policy.pattern }}
        pattern:
{{ toYaml .Values.kyverno.policy.pattern | nindent 10 }}
        {{- else }}
        # default (sane) pattern if none supplied
        pattern:
{{ toYaml (dict "spec" (dict "forProvider" (dict "publiclyAccessible" false "deletionProtection" true))) | nindent 10 }}
        {{- end }}
{{- end }}
