apiVersion: v1
kind: Service
metadata:
  name: {{ include "nginx.fullname" . }}
spec:
  type: {{ .Values.nginx.service.type }}
  selector:
    app: nginx
  ports:
    - port: {{ .Values.nginx.service.port }}
      targetPort: 80
