# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRole
# metadata:
#   name: kyverno-crossplane-rdsinstance-access
# rules:
#   - apiGroups: ["database.aws.crossplane.io"]
#     resources: ["rdsinstances"]
#     verbs: ["get", "list", "watch"]

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: kyverno-crossplane-rdsinstance-access-binding
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: kyverno-crossplane-rdsinstance-access
# subjects:
#   - kind: ServiceAccount
#     name: kyverno-reports-controller
#     namespace: kyverno

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kyverno-crossplane-rdsinstance-access
rules:
  - apiGroups: ["database.aws.crossplane.io"]
    resources: ["rdsinstances"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kyverno-crossplane-rdsinstance-access-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kyverno-crossplane-rdsinstance-access
subjects:
  - kind: ServiceAccount
    name: {{ .Values.kyverno.serviceAccount }}
    namespace: {{ .Values.kyverno.namespace }}
