{{- if .Values.rds.enabled }}
{{- /* Resolve namespace with sensible fallbacks */ -}}
{{- $ns := default .Release.Namespace .Values.rds.namespace -}}

{{- if .Values.apps }}
  {{- range .Values.apps }}
    {{- if eq .name $.Release.Name }}
      {{- $ns = .namespace }}
    {{- end }}
  {{- end }}
{{- end }}

apiVersion: database.aws.crossplane.io/v1beta1
kind: RDSInstance
metadata:
  name: {{ default .Release.Name .Values.rds.name }}
  namespace: {{ $ns }}
  annotations:
    # Put RDS after ProviderConfig to avoid creds timing issues in Argo CD
    argocd.argoproj.io/sync-wave: "2"
spec:
  forProvider:
    allocatedStorage: {{ .Values.rds.forProvider.allocatedStorage }}
    autoMinorVersionUpgrade: {{ .Values.rds.forProvider.autoMinorVersionUpgrade }}
    backupRetentionPeriod: {{ .Values.rds.forProvider.backupRetentionPeriod }}
    caCertificateIdentifier: {{ .Values.rds.forProvider.caCertificateIdentifier | quote }}
    dbInstanceClass: {{ .Values.rds.forProvider.dbInstanceClass | quote }}
    deletionProtection: {{ .Values.rds.forProvider.deletionProtection }}
    enableIAMDatabaseAuthentication: {{ .Values.rds.forProvider.enableIAMDatabaseAuthentication }}
    engine: {{ .Values.rds.forProvider.engine | quote }}
    engineVersion: {{ .Values.rds.forProvider.engineVersion | quote }}
    masterUsername: {{ .Values.rds.forProvider.masterUsername | quote }}
    multiAZ: {{ .Values.rds.forProvider.multiAZ }}
    port: {{ .Values.rds.forProvider.port }}
    publiclyAccessible: {{ .Values.rds.forProvider.publiclyAccessible }}
    region: {{ .Values.rds.forProvider.region | quote }}
    storageEncrypted: {{ .Values.rds.forProvider.storageEncrypted }}
    storageType: {{ .Values.rds.forProvider.storageType | quote }}
  providerConfigRef:
    name: {{ .Values.rds.providerConfigRefName | default "aws" | quote }}
{{- end }}
