rds:
  enabled: true
  name: example-rds-test-01
  namespace: crossplane-system
  providerConfigRefName: aws
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-rsa2048-g1
    dbInstanceClass: db.r5.large
    deletionProtection: false        # <- deliberately unsafe (to test the policy)
    enableIAMDatabaseAuthentication: false
    engine: mysql
    engineVersion: "8.0.42"
    masterUsername: admin
    multiAZ: true
    port: 3306
    publiclyAccessible: true         # <- deliberately unsafe (to test the policy)
    region: us-east-1
    storageEncrypted: false
    storageType: gp2
