nginx:
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.25.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}
  
rds:
  enabled: true
  providerConfigRefName: aws
  deletionPolicy: Orphan        # ✅ don’t delete DB on MR removal
  managementPolicy: FullControl # ✅ Crossplane manages lifecycle
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0             # ❌ Will be blocked by policy
    caCertificateIdentifier: rds-ca-rsa2048-g1
    dbInstanceClass: db.r5.large
    deletionProtection: false            # ❌ Will be blocked
    enableIAMDatabaseAuthentication: false
    engine: mysql
    engineVersion: "8.0.42"              # ✅ Allowed (can be enforced)
    masterUsername: admin
    multiAZ: true
    port: 3306
    publiclyAccessible: false            # ❌ Will be blocked
    region: us-east-1
    storageEncrypted: false              # ❌ Will be blocked
    storageType: gp2

validationFailureAction: Enforce

kyverno:
  serviceAccount: kyverno-reports-controller
  namespace: kyverno

policy:
  enabled: true
  message: "RDS security policy requirement not met."
  enforcePublicAccess: true
  enforceDeletionProtection: true
  enforceEncryption: true
  enforceBackupRetention: true
  minBackupRetention: 7
  enforceEngine: true
  allowedEngine: mysql
  allowedEngineVersion: "8.0.*"
