# rds-guard/values.yaml
nginx:
  replicaCount: 2
  image:
    repository: nginx
    tag: "1.25.0"
    pullPolicy: IfNotPresent
  service:
    type: ClusterIP
    port: 80
  resources: {}

rds:
  enabled: true
  # providerConfigRefName: aws
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-rsa2048-g1
    dbInstanceClass: db.r5.large
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    engine: mysql
    engineVersion: "8.0.42"
    masterUsername: admin
    multiAZ: true
    port: 3306
    publiclyAccessible: true
    region: us-east-1
    storageEncrypted: false
    storageType: gp2

validationFailureAction: Enforce

kyverno:
  serviceAccount: kyverno-reports-controller
  namespace: kyverno

policy:
  enabled: true
  message: "RDS instances must not be publicly accessible and must have deletion protection enabled."
  enforcePublicAccess: false
  enforceDeletionProtection: false
