# rds-guard/values.yaml
rds:
  enabled: true
  providerConfigRefName: aws
  forProvider:
    allocatedStorage: 20
    autoMinorVersionUpgrade: true
    backupRetentionPeriod: 0
    caCertificateIdentifier: rds-ca-rsa2048-g1
    dbInstanceClass: db.r5.large
    deletionProtection: false
    enableIAMDatabaseAuthentication: false
    engine: mysql
    engineVersion: "8.0.42"
    masterUsername: admin
    multiAZ: true
    port: 3306
    publiclyAccessible: true
    region: us-east-1
    storageEncrypted: false
    storageType: gp2

kyverno:
  enabled: false
  policy:
    name: disallow-public-rds
    validationFailureAction: Enforce   # or Audit
    background: true
    message: "prequirement not met:"   # your custom message

    # match target kinds (full GVK string(s))
    match:
      kinds:
        - database.aws.crossplane.io/v1beta1/RDSInstance
    # EITHER supply `pattern:` (single map)...
    pattern:
      spec:
        forProvider:
          publiclyAccessible: false
          deletionProtection: true

    # ...OR supply `anyPattern:` (list of maps). If provided, it overrides `pattern`.
    # anyPattern:
    #   - spec:
    #       forProvider:
    #         publiclyAccessible: false
    #         deletionProtection: true
    #   - spec:
    #       forProvider:
    #         publiclyAccessible: "false"   # example showing string coercion variant
