provider:
  enabled: true
  name: provider-aws
  package: "xpkg.upbound.io/crossplane-contrib/provider-aws:v0.54.2"
controllerConfig:
  enabled: false
  name: aws-controller
  spec:
    args: []
    nodeSelector: {}
    tolerations: []
    env: []
providerConfig:
  enabled: true
  name: aws
  credentials:
    source: Secret
    secretRef:
      name: aws-creds
      namespace: crossplane-system
      key: creds
