# Optional: set once, auto-applies to secretRef.namespace.
# If omitted, it will default to the Argo CD Application's destination.namespace
# (i.e., .Release.Namespace in Helm).
global:
  targetNamespace: ""
providers:
  aws:
    enabled: true
    name: provider-aws
    package: xpkg.upbound.io/crossplane-contrib/provider-aws:v0.54.2
  gcp:
    enabled: false
    name: provider-gcp
    package: xpkg.upbound.io/crossplane-contrib/provider-gcp:v0.22.0
  azure:
    enabled: false
    name: provider-azure
    package: xpkg.upbound.io/crossplane-contrib/provider-azure:v0.20.1
