{{- if .Values.cluster.createCluster }}
apiVersion: eks.aws.crossplane.io/v1beta1
kind: Cluster
metadata:
  name: {{ .Values.cluster.name }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  forProvider:
    region: {{ .Values.cluster.region }}
    version: {{ .Values.cluster.version | quote }}
    resourcesVpcConfig:
      endpointPrivateAccess: false
      endpointPublicAccess: true
      securityGroupIds:
{{- range .Values.cluster.securityGroupIds }}
        - {{ . | quote }}
{{- end }}
      subnetIds:
{{- range .Values.cluster.subnetIds }}
        - {{ . | quote }}
{{- end }}
    roleArn: {{ .Values.cluster.roleArn }}
  providerConfigRef:
    name: {{ .Values.providerConfig.name }}
  writeConnectionSecretToRef:
    name: {{ .Values.cluster.connectionSecret.name }}
    namespace: {{ .Values.cluster.connectionSecret.namespace }}
{{- end }}
